version: '3'
services:
  dividitto-app:
    restart: unless-stopped
    build: .
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: 0
      VIRTUAL_HOST: ${NGNIX_HOST}
      LETSENCRYPT_HOST: ${NGNIX_HOST}
      LETSENCRYPT_EMAIL: ${NGNIX_EMAIL}
      VIRTUAL_PORT: 80
    expose:
      - 80
      
networks:
  default:
    external:
      name: cloud-network
