version: '3'
services:
  db:
    image: 'postgres:15.4-alpine3.18'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dividitto
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    command: "-c timezone=America/Argentina/Buenos_Aires -c log_timezone=America/Argentina/Buenos_Aires"