# Generated by Django 4.2.4 on 2023-08-31 20:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('percentage', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-user'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField()),
                ('value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('is_settle', models.BooleanField(default=False)),
                ('net_value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.UniqueConstraint(fields=('month', 'year', 'user'), name='income_pk'),
        ),
    ]
