# Generated by Django 4.2.4 on 2023-08-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expense_net_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='net_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
