# Generated by Django 4.2.4 on 2023-08-27 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_expense_net_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='net_value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
