# Generated by Django 4.2.4 on 2023-08-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_income'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='income',
            constraint=models.UniqueConstraint(fields=('month', 'year', 'user'), name='income_pk'),
        ),
    ]
